// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApc_0E83QYxjn4QiFLMoaOh8DHZIVhWAo',
    appId: '1:44488471486:web:ec579ba2f62de86499bfef',
    messagingSenderId: '44488471486',
    projectId: 'nimmyscrm',
    authDomain: 'nimmyscrm.firebaseapp.com',
    storageBucket: 'nimmyscrm.firebasestorage.app',
    measurementId: 'G-26Z7P09YDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB98sz9hyUevNr3hj5S3iRFBUHUtkVZKdc',
    appId: '1:44488471486:android:f2eb95b65fdc25bf99bfef',
    messagingSenderId: '44488471486',
    projectId: 'nimmyscrm',
    storageBucket: 'nimmyscrm.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD51N_hfaRamsRbiBxXxH7BoHA1LJosa4w',
    appId: '1:44488471486:ios:f08bcef11ccd763b99bfef',
    messagingSenderId: '44488471486',
    projectId: 'nimmyscrm',
    storageBucket: 'nimmyscrm.firebasestorage.app',
    iosBundleId: 'com.nimmyscrm.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD51N_hfaRamsRbiBxXxH7BoHA1LJosa4w',
    appId: '1:44488471486:ios:f08bcef11ccd763b99bfef',
    messagingSenderId: '44488471486',
    projectId: 'nimmyscrm',
    storageBucket: 'nimmyscrm.firebasestorage.app',
    iosBundleId: 'com.nimmyscrm.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApc_0E83QYxjn4QiFLMoaOh8DHZIVhWAo',
    appId: '1:44488471486:web:2cd3e0b1f61c27e299bfef',
    messagingSenderId: '44488471486',
    projectId: 'nimmyscrm',
    authDomain: 'nimmyscrm.firebaseapp.com',
    storageBucket: 'nimmyscrm.firebasestorage.app',
    measurementId: 'G-1MTKJP2ZJS',
  );
}
